<?php

namespace AppBundle\Repository;

/**
 * HerokuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HerokuRepository extends \Doctrine\ORM\EntityRepository
{
}
